name: CI - API & E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run API and E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install root dependencies
        run: npm ci

      - name: Install server dependencies
        working-directory: server
        run: npm ci

      - name: Start mock server
        working-directory: server
        run: |
          npm run ci &
          sleep 3

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman API Tests
        run: npx newman run api-tests/qa-tools-portal.collection.json -e api-tests/local.environment.json

      - name: Install Playwright dependencies
        working-directory: e2e-tests
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run Playwright E2E Tests
        working-directory: e2e-tests
        run: npx playwright test